version: '3.8'

services:
  db:
    image: postgres:14
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "
      until nc -z db 5432; do
        echo 'Waiting for the database...';
        sleep 1;
      done;
      python manage.py migrate &&
      python manage.py populate_data &&
      python manage.py createsuperuser --noinput --username admin --email admin@example.com || true &&
      python manage.py collectstatic --noinput &&
      python manage.py runserver 0.0.0.0:8000
      "
    env_file: .env
    volumes:
      - .:/app
      - static_volume:/app/static  # Volume для статических файлов
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:  # Volume для хранения статических файлов
